export { SupabasePlugin, SupabasePlugin as default } from './plugin/SupabasePlugin'
export { useClient } from './composables/useClient'
export { useApi, UseApiReturn } from './composables/useApi'
export { useModelApi, UseModelApiReturn } from './composables/useModelApi'
export { useModel, UseModelReturn } from './composables/useModel'
export { useModelCollection, UseModelCollectionReturn } from './composables/useModelCollection'
